# These are supported funding model platforms

custom: ['https://raw.githubusercontent.com/RongKaCZ/storyscience/main/assets/wechat.jpg', 'https://raw.githubusercontent.com/RongKaCZ/storyscience/main/assets/alipay.jpg']